-- Reapply the frozen position defaults after making tenant discovery safe for
-- the non-BYPASSRLS migration owner. V35 was intentionally idempotent, but a
-- fresh Flyway connection could see zero tenant rows while tenant FORCE RLS was
-- active and therefore complete without publishing any profile. This migration
-- repeats the guarded V35 logic and restores FORCE RLS in the same transaction.

-- Publish the frozen position/function defaults only for untouched blank
-- V1 drafts generated by V33.  This migration is deliberately fail-closed:
-- custom drafts, published history, hotel overrides and hotel applicability
-- changes are never rewritten.

-- Split the cross-hotel cockpit from the single-hotel cockpit.  The original
-- dashboard.hotel permission remains the prerequisite for opening one hotel;
-- dashboard.operations is independently configurable for regional aggregation.
INSERT INTO permission (
    code, resource, action, description, delegable_to_position, function_category
) VALUES (
    'dashboard.operations', 'dashboard', 'operations', '查看授权范围的区域多门店驾驶舱', true, 'DASHBOARD'
)
ON CONFLICT (code) DO UPDATE
SET resource = EXCLUDED.resource,
    action = EXCLUDED.action,
    description = EXCLUDED.description,
    delegable_to_position = true,
    function_category = 'DASHBOARD';

CREATE TEMP TABLE v36_position_scope_matrix (
    position_code VARCHAR(64) PRIMARY KEY,
    authorization_scope_type VARCHAR(24) NOT NULL
        CHECK (authorization_scope_type IN ('SELF', 'ORG_UNIT', 'ORG_TREE', 'TENANT'))
) ON COMMIT DROP;

INSERT INTO v36_position_scope_matrix (position_code, authorization_scope_type) VALUES
    ('FRONT_DESK', 'SELF'),
    ('HOUSEKEEPING_ATTENDANT', 'SELF'),
    ('OTA_OPERATION_ASSISTANT', 'SELF'),
    ('FRONT_OFFICE_SUPERVISOR', 'ORG_UNIT'),
    ('HOUSEKEEPING_SUPERVISOR', 'ORG_UNIT'),
    ('ASSISTANT_GENERAL_MANAGER', 'ORG_TREE'),
    ('GENERAL_MANAGER', 'ORG_TREE'),
    ('OTA_OPERATION_MANAGER', 'ORG_TREE'),
    ('GROUP_VICE_PRESIDENT', 'ORG_TREE'),
    ('HR_KPI_ADMIN', 'TENANT');

CREATE TEMP TABLE v36_position_permission_matrix (
    position_code VARCHAR(64) NOT NULL
        REFERENCES v36_position_scope_matrix (position_code),
    permission_code VARCHAR(120) NOT NULL,
    PRIMARY KEY (position_code, permission_code)
) ON COMMIT DROP;

-- Front-line employees: own work, own daily report, own tasks and own KPI.
INSERT INTO v36_position_permission_matrix (position_code, permission_code)
SELECT position_code, permission_code
FROM unnest(ARRAY['FRONT_DESK', 'HOUSEKEEPING_ATTENDANT']) AS positions(position_code)
CROSS JOIN unnest(ARRAY[
    'org.read',
    'standard.read',
    'work.submit',
    'work-package.read',
    'work-record.read',
    'work-record.submit',
    'task.read',
    'task.act',
    'evaluation.read',
    'notification.read',
    'daily-report.read',
    'daily-report.submit',
    'daily-report-template.read',
    'kpi.metric.read',
    'kpi.template.read',
    'kpi.scorecard.read-own',
    'kpi.scorecard.dispute'
]) AS permissions(permission_code);

-- OTA assistant: employee self-service plus assigned OTA inspection submission;
-- the evaluation module is intentionally not included in this position.
INSERT INTO v36_position_permission_matrix (position_code, permission_code)
SELECT 'OTA_OPERATION_ASSISTANT', permission_code
FROM unnest(ARRAY[
    'org.read',
    'standard.read',
    'work.submit',
    'work-package.read',
    'work-record.read',
    'work-record.submit',
    'task.read',
    'task.act',
    'notification.read',
    'daily-report.read',
    'daily-report.submit',
    'daily-report-template.read',
    'kpi.metric.read',
    'kpi.template.read',
    'kpi.scorecard.read-own',
    'kpi.scorecard.dispute',
    'kpi.inspection.submit'
]) AS permissions(permission_code);

-- Department supervisors: employee capabilities plus team review, dispatch,
-- departmental daily operation and departmental KPI handling.
INSERT INTO v36_position_permission_matrix (position_code, permission_code)
SELECT position_code, permission_code
FROM unnest(ARRAY['FRONT_OFFICE_SUPERVISOR', 'HOUSEKEEPING_SUPERVISOR'])
    AS positions(position_code)
CROSS JOIN unnest(ARRAY[
    'org.read',
    'standard.read',
    'work.submit',
    'work-package.read',
    'work-record.read',
    'work-record.submit',
    'work-record.review',
    'task.read',
    'task.create',
    'task.dispatch',
    'task.act',
    'task.review',
    'evaluation.read',
    'evaluation.manual-review',
    'notification.read',
    'daily-report.read',
    'daily-report.submit',
    'daily-report.team-read',
    'daily-report.review',
    'daily-report.revision-review',
    'daily-report-template.read',
    'daily-operation.read',
    'issue.confirm',
    'issue.assign',
    'issue.close',
    'issue.reopen',
    'kpi.metric.read',
    'kpi.template.read',
    'kpi.scorecard.read-own',
    'kpi.scorecard.read-team',
    'kpi.scorecard.manual-score',
    'kpi.scorecard.review',
    'kpi.scorecard.dispute'
]) AS permissions(permission_code);

-- Assistant general manager: store dashboard, store exception/candidate loop and
-- store-specific report-template supplements in addition to supervisor duties.
INSERT INTO v36_position_permission_matrix (position_code, permission_code)
SELECT 'ASSISTANT_GENERAL_MANAGER', permission_code
FROM unnest(ARRAY[
    'org.read',
    'standard.read',
    'dashboard.hotel',
    'work.submit',
    'work-package.read',
    'work-record.read',
    'work-record.submit',
    'work-record.review',
    'task.read',
    'task.create',
    'task.dispatch',
    'task.act',
    'task.review',
    'task.cancel',
    'evaluation.read',
    'evaluation.manual-review',
    'notification.read',
    'daily-report.read',
    'daily-report.submit',
    'daily-report.team-read',
    'daily-report.review',
    'daily-report.revision-review',
    'daily-report-template.read',
    'daily-report-template.store-supplement',
    'daily-operation.read',
    'issue.confirm',
    'issue.assign',
    'issue.close',
    'issue.reopen',
    'task-candidate.read',
    'task-candidate.manage',
    'task-candidate.confirm',
    'task-candidate.reject',
    'task-candidate.retry',
    'operation-snapshot.read',
    'kpi.metric.read',
    'kpi.template.read',
    'kpi.scorecard.read-own',
    'kpi.scorecard.read-team',
    'kpi.scorecard.manual-score',
    'kpi.scorecard.review',
    'kpi.scorecard.dispute'
]) AS permissions(permission_code);

-- General manager: assistant-GM store loop plus rule reading, snapshot recovery
-- and non-sensitive operational export.
INSERT INTO v36_position_permission_matrix (position_code, permission_code)
SELECT 'GENERAL_MANAGER', permission_code
FROM unnest(ARRAY[
    'org.read',
    'standard.read',
    'dashboard.hotel',
    'work.submit',
    'work-package.read',
    'work-record.read',
    'work-record.submit',
    'work-record.review',
    'task.read',
    'task.create',
    'task.dispatch',
    'task.act',
    'task.review',
    'task.cancel',
    'evaluation.read',
    'evaluation.manual-review',
    'notification.read',
    'daily-report.read',
    'daily-report.submit',
    'daily-report.team-read',
    'daily-report.review',
    'daily-report.revision-review',
    'daily-report-template.read',
    'daily-report-template.store-supplement',
    'daily-operation.read',
    'issue.confirm',
    'issue.assign',
    'issue.close',
    'issue.reopen',
    'task-candidate.read',
    'task-candidate.manage',
    'task-candidate.confirm',
    'task-candidate.reject',
    'task-candidate.retry',
    'rule.read',
    'operation-snapshot.read',
    'operation-snapshot.retry',
    'operation-snapshot.compare',
    'operation-export.create',
    'operation-export.download',
    'kpi.metric.read',
    'kpi.template.read',
    'kpi.scorecard.read-own',
    'kpi.scorecard.read-team',
    'kpi.scorecard.manual-score',
    'kpi.scorecard.review',
    'kpi.scorecard.dispute'
]) AS permissions(permission_code);

-- Regional/OTA operations manager: cross-hotel operation, regional task/report
-- loop, rule simulation, regional export and OTA inspection verification.
INSERT INTO v36_position_permission_matrix (position_code, permission_code)
SELECT 'OTA_OPERATION_MANAGER', permission_code
FROM unnest(ARRAY[
    'org.read',
    'standard.read',
    'dashboard.hotel',
    'dashboard.operations',
    'work.submit',
    'work-package.read',
    'work-record.read',
    'work-record.submit',
    'work-record.review',
    'task.read',
    'task.create',
    'task.dispatch',
    'task.act',
    'task.review',
    'task.cancel',
    'notification.read',
    'daily-report.read',
    'daily-report.submit',
    'daily-report.team-read',
    'daily-report.review',
    'daily-report.revision-review',
    'daily-report-template.read',
    'daily-operation.read',
    'daily-operation.cross-hotel-read',
    'issue.confirm',
    'issue.assign',
    'issue.close',
    'issue.reopen',
    'task-candidate.read',
    'task-candidate.manage',
    'task-candidate.confirm',
    'task-candidate.reject',
    'task-candidate.retry',
    'rule.read',
    'rule.simulate',
    'operation-snapshot.read',
    'operation-snapshot.retry',
    'operation-snapshot.compare',
    'operation-export.create',
    'operation-export.download',
    'kpi.metric.read',
    'kpi.template.read',
    'kpi.scorecard.read-own',
    'kpi.scorecard.read-team',
    'kpi.scorecard.manual-score',
    'kpi.scorecard.review',
    'kpi.scorecard.dispute',
    'kpi.inspection.submit',
    'kpi.inspection.read-team',
    'kpi.inspection.verify'
]) AS permissions(permission_code);

-- Group vice president: cross-hotel business reading and assigned task actions.
-- No investment, IAM, secret, webhook or system-configuration capability is
-- delegated through the position.
INSERT INTO v36_position_permission_matrix (position_code, permission_code)
SELECT 'GROUP_VICE_PRESIDENT', permission_code
FROM unnest(ARRAY[
    'org.read',
    'standard.read',
    'dashboard.hotel',
    'dashboard.operations',
    'work-package.read',
    'task.read',
    'task.act',
    'notification.read',
    'daily-report.read',
    'daily-report.team-read',
    'daily-operation.read',
    'daily-operation.cross-hotel-read',
    'rule.read',
    'operation-snapshot.read',
    'operation-snapshot.compare',
    'operation-export.create',
    'operation-export.download',
    'kpi.metric.read',
    'kpi.template.read',
    'kpi.scorecard.read-own',
    'kpi.scorecard.read-team',
    'kpi.settlement.read'
]) AS permissions(permission_code);

-- HR is optional: this matrix applies only when an HR_KPI_ADMIN position (not
-- merely the supplemental account role) already existed when V33 ran.  WeCom,
-- organization administration and position-profile administration remain
-- protected account-level grants and are intentionally absent here.
INSERT INTO v36_position_permission_matrix (position_code, permission_code)
SELECT 'HR_KPI_ADMIN', permission_code
FROM unnest(ARRAY[
    'org.read',
    'task.read',
    'task.act',
    'notification.read',
    'kpi.metric.read',
    'kpi.metric.manage',
    'kpi.template.read',
    'kpi.template.manage',
    'kpi.template.review',
    'kpi.template.publish',
    'kpi.template.import',
    'kpi.relation.manage',
    'kpi.scorecard.read-own',
    'kpi.scorecard.read-team',
    'kpi.scorecard.generate',
    'kpi.scorecard.manual-score',
    'kpi.scorecard.review',
    'kpi.scorecard.dispute',
    'kpi.scorecard.lock',
    'kpi.settlement.read',
    'kpi.inspection.read-team',
    'kpi.inspection.verify'
]) AS permissions(permission_code);

-- Validate the reviewed allowlist before touching tenant data.  A permission
-- introduced with a different protection classification must stop the entire
-- migration instead of silently broadening or truncating a position profile.
DO $$
DECLARE
    invalid_codes TEXT;
BEGIN
    SELECT string_agg(matrix.permission_code, ', ' ORDER BY matrix.permission_code)
      INTO invalid_codes
      FROM (
          SELECT DISTINCT permission_code
          FROM v36_position_permission_matrix
      ) matrix
      LEFT JOIN permission permission_item
        ON permission_item.code = matrix.permission_code
       AND permission_item.delegable_to_position = true
     WHERE permission_item.id IS NULL;

    IF invalid_codes IS NOT NULL THEN
        RAISE EXCEPTION 'V36 position matrix contains unknown or protected permissions: %', invalid_codes;
    END IF;

    IF EXISTS (
        SELECT 1 FROM v36_position_scope_matrix
        WHERE position_code IN ('CEO', 'PLATFORM_ADMIN')
    ) THEN
        RAISE EXCEPTION 'V36 position matrix cannot delegate account-level administrator roles';
    END IF;
END $$;

-- The migration role owns tenant but is deliberately NOBYPASSRLS. Removing
-- FORCE lets only that owner enumerate tenant ids; every tenant-scoped table
-- remains protected, and the loop restores app.tenant_id before accessing it.
-- PostgreSQL transactional DDL guarantees FORCE RLS is restored on rollback.
ALTER TABLE tenant NO FORCE ROW LEVEL SECURITY;

DO $$
DECLARE
    tenant_record RECORD;
    candidate RECORD;
    publishing_actor UUID;
    next_draft_id UUID;
    expected_permission_count INTEGER;
    inserted_permission_count INTEGER;
    promoted_count INTEGER;
BEGIN
    FOR tenant_record IN SELECT id FROM tenant ORDER BY id LOOP
        PERFORM set_config('app.tenant_id', tenant_record.id::text, true);

        INSERT INTO role_permission (tenant_id, role_id, permission_id)
        SELECT tenant_record.id, role.id, permission_item.id
        FROM app_role role
        JOIN permission permission_item
          ON permission_item.code = 'dashboard.operations'
        WHERE role.tenant_id = tenant_record.id
          AND role.code IN ('CEO', 'OTA_OPERATION_MANAGER', 'GROUP_VICE_PRESIDENT')
        ON CONFLICT DO NOTHING;

        -- Positions created or restored after V33 can legitimately have no
        -- group profile yet.  Without the profile, EffectiveIdentityService
        -- rejects an otherwise active employee assignment during /iam/me and
        -- the browser appears to log in and immediately return to the login
        -- screen.  Backfill only reviewed frozen position codes whose matching
        -- role already exists; custom positions and mismatched role mappings
        -- remain untouched.
        INSERT INTO position_function_profile (
            id, tenant_id, position_id, scope_type, default_role_id
        )
        SELECT gen_random_uuid(), tenant_record.id, position_item.id, 'GROUP', mapped_role.id
        FROM position_definition position_item
        JOIN v36_position_scope_matrix matrix
          ON matrix.position_code = position_item.code
        JOIN app_role mapped_role
          ON mapped_role.tenant_id = position_item.tenant_id
         AND mapped_role.code = position_item.code
        WHERE position_item.tenant_id = tenant_record.id
          AND position_item.status = 'ACTIVE'
          AND position_item.deleted_at IS NULL
          AND position_item.permanently_deleted_at IS NULL
          AND NOT EXISTS (
              SELECT 1
              FROM position_function_profile existing_profile
              WHERE existing_profile.tenant_id = position_item.tenant_id
                AND existing_profile.position_id = position_item.id
                AND existing_profile.scope_type = 'GROUP'
          )
          AND NOT EXISTS (
              SELECT 1
              FROM position_function_profile role_profile
              WHERE role_profile.tenant_id = mapped_role.tenant_id
                AND role_profile.default_role_id = mapped_role.id
                AND role_profile.scope_type = 'GROUP'
          )
        ON CONFLICT DO NOTHING;

        -- A just-created profile receives the same pristine V1 draft shape as
        -- V33.  An older incomplete profile also gets a recoverable draft, but
        -- the timestamp equality guard below prevents it from being silently
        -- auto-published as if it had just been created here.
        INSERT INTO position_function_profile_version (
            id, tenant_id, profile_id, version_no, lifecycle_status
        )
        SELECT gen_random_uuid(), profile.tenant_id, profile.id, 1, 'DRAFT'
        FROM position_function_profile profile
        JOIN position_definition position_item
          ON position_item.tenant_id = profile.tenant_id
         AND position_item.id = profile.position_id
        JOIN v36_position_scope_matrix matrix
          ON matrix.position_code = position_item.code
        JOIN app_role mapped_role
          ON mapped_role.tenant_id = profile.tenant_id
         AND mapped_role.id = profile.default_role_id
         AND mapped_role.code = position_item.code
        WHERE profile.tenant_id = tenant_record.id
          AND profile.scope_type = 'GROUP'
          AND NOT EXISTS (
              SELECT 1
              FROM position_function_profile_version existing_version
              WHERE existing_version.tenant_id = profile.tenant_id
                AND existing_version.profile_id = profile.id
          );

        SELECT account.id
          INTO publishing_actor
          FROM user_account account
          JOIN role_assignment assignment
            ON assignment.tenant_id = account.tenant_id
           AND assignment.account_id = account.id
          JOIN app_role role
            ON role.tenant_id = assignment.tenant_id
           AND role.id = assignment.role_id
         WHERE account.tenant_id = tenant_record.id
           AND account.status = 'ACTIVE'
           AND role.code IN ('PLATFORM_ADMIN', 'CEO')
           AND assignment.scope_type = 'TENANT'
           AND assignment.valid_from <= now()
           AND (assignment.valid_to IS NULL OR assignment.valid_to > now())
         ORDER BY CASE role.code WHEN 'PLATFORM_ADMIN' THEN 0 ELSE 1 END,
                  account.id
         LIMIT 1;

        -- No authorized publisher means no automatic publication for this
        -- tenant.  Keeping the V33 draft untouched is safer than inventing an
        -- audit actor or weakening the foreign-key/audit boundary.
        IF publishing_actor IS NULL THEN
            CONTINUE;
        END IF;

        FOR candidate IN
            SELECT
                position_item.id AS position_id,
                position_item.code AS position_code,
                profile.id AS profile_id,
                profile.default_role_id,
                draft.id AS draft_id,
                matrix.authorization_scope_type
            FROM position_definition position_item
            JOIN v36_position_scope_matrix matrix
              ON matrix.position_code = position_item.code
            JOIN position_function_profile profile
              ON profile.tenant_id = position_item.tenant_id
             AND profile.position_id = position_item.id
             AND profile.scope_type = 'GROUP'
            JOIN app_role mapped_role
              ON mapped_role.tenant_id = profile.tenant_id
             AND mapped_role.id = profile.default_role_id
             AND mapped_role.code = position_item.code
            JOIN position_function_profile_version draft
              ON draft.tenant_id = profile.tenant_id
             AND draft.profile_id = profile.id
             AND draft.version_no = 1
             AND draft.lifecycle_status = 'DRAFT'
            WHERE position_item.tenant_id = tenant_record.id
              AND position_item.status = 'ACTIVE'
              AND position_item.deleted_at IS NULL
              AND position_item.permanently_deleted_at IS NULL
              AND position_item.row_version = 0
              AND position_item.applies_to_all_hotels = true
              AND profile.row_version = 0
              AND profile.created_at = profile.updated_at
              AND draft.row_version = 0
              AND draft.authorization_scope_type = 'SELF'
              AND draft.wecom_self_selectable = false
              AND draft.created_by IS NULL
              AND draft.published_by IS NULL
              AND draft.published_at IS NULL
              AND draft.copied_from_version_id IS NULL
              AND draft.based_on_group_version_id IS NULL
              AND draft.created_at = draft.updated_at
              AND draft.created_at = profile.created_at
              AND NOT EXISTS (
                  SELECT 1
                  FROM position_function_profile_permission assigned_permission
                  WHERE assigned_permission.tenant_id = draft.tenant_id
                    AND assigned_permission.profile_version_id = draft.id
              )
              AND NOT EXISTS (
                  SELECT 1
                  FROM position_function_profile_version other_version
                  WHERE other_version.tenant_id = profile.tenant_id
                    AND other_version.profile_id = profile.id
                    AND other_version.id <> draft.id
              )
              AND NOT EXISTS (
                  SELECT 1
                  FROM position_function_profile hotel_profile
                  WHERE hotel_profile.tenant_id = position_item.tenant_id
                    AND hotel_profile.position_id = position_item.id
                    AND hotel_profile.scope_type = 'HOTEL'
              )
              AND NOT EXISTS (
                  SELECT 1
                  FROM position_applicable_hotel applicable_hotel
                  WHERE applicable_hotel.tenant_id = position_item.tenant_id
                    AND applicable_hotel.position_id = position_item.id
              )
            ORDER BY position_item.code
            FOR UPDATE OF position_item, profile, draft
        LOOP
            SELECT count(*)
              INTO expected_permission_count
              FROM v36_position_permission_matrix
             WHERE position_code = candidate.position_code;

            INSERT INTO position_function_profile_permission
                (tenant_id, profile_version_id, permission_id)
            SELECT tenant_record.id, candidate.draft_id, permission_item.id
            FROM v36_position_permission_matrix matrix
            JOIN permission permission_item
              ON permission_item.code = matrix.permission_code
             AND permission_item.delegable_to_position = true
            WHERE matrix.position_code = candidate.position_code;

            GET DIAGNOSTICS inserted_permission_count = ROW_COUNT;
            IF inserted_permission_count <> expected_permission_count THEN
                RAISE EXCEPTION 'V36 position profile permission count mismatch for %',
                    candidate.position_code;
            END IF;

            UPDATE position_function_profile_version
               SET lifecycle_status = 'PUBLISHED',
                   authorization_scope_type = candidate.authorization_scope_type,
                   published_by = publishing_actor,
                   published_at = now(),
                   row_version = row_version + 1,
                   updated_at = now()
             WHERE tenant_id = tenant_record.id
               AND id = candidate.draft_id
               AND lifecycle_status = 'DRAFT'
               AND version_no = 1
               AND row_version = 0;

            GET DIAGNOSTICS promoted_count = ROW_COUNT;
            IF promoted_count <> 1 THEN
                RAISE EXCEPTION 'V36 position profile changed concurrently for %',
                    candidate.position_code;
            END IF;

            next_draft_id := gen_random_uuid();
            INSERT INTO position_function_profile_version (
                id, tenant_id, profile_id, version_no, lifecycle_status,
                copied_from_version_id, authorization_scope_type,
                wecom_self_selectable, created_by
            ) VALUES (
                next_draft_id, tenant_record.id, candidate.profile_id, 2, 'DRAFT',
                candidate.draft_id, candidate.authorization_scope_type,
                false, publishing_actor
            );

            INSERT INTO position_function_profile_permission
                (tenant_id, profile_version_id, permission_id)
            SELECT tenant_id, next_draft_id, permission_id
            FROM position_function_profile_permission
            WHERE tenant_id = tenant_record.id
              AND profile_version_id = candidate.draft_id;

            -- Synchronize only the delegable subset used by legacy endpoints.
            -- Protected account-level grants survive unchanged.
            DELETE FROM role_permission role_grant
            USING permission permission_item
            WHERE role_grant.tenant_id = tenant_record.id
              AND role_grant.role_id = candidate.default_role_id
              AND permission_item.id = role_grant.permission_id
              AND permission_item.delegable_to_position = true;

            INSERT INTO role_permission (tenant_id, role_id, permission_id)
            SELECT tenant_record.id, candidate.default_role_id, permission_item.id
            FROM v36_position_permission_matrix matrix
            JOIN permission permission_item
              ON permission_item.code = matrix.permission_code
             AND permission_item.delegable_to_position = true
            WHERE matrix.position_code = candidate.position_code
            ON CONFLICT DO NOTHING;

            UPDATE position_function_profile
               SET row_version = row_version + 1,
                   updated_at = now()
             WHERE tenant_id = tenant_record.id
               AND id = candidate.profile_id;

            UPDATE position_definition
               SET row_version = row_version + 1,
                   updated_at = now()
             WHERE tenant_id = tenant_record.id
               AND id = candidate.position_id
               AND row_version = 0;

            -- One aggregate, privacy-safe system audit record per automatic
            -- publication.  It contains no account details, employee data,
            -- credentials, tokens or tenant business content.
            INSERT INTO audit_log (
                tenant_id, actor_id, action, resource_type, resource_id,
                correlation_id, after_data
            ) VALUES (
                tenant_record.id,
                publishing_actor,
                'SYSTEM_POSITION_PROFILE_DEFAULT_PUBLISHED',
                'POSITION_FUNCTION_PROFILE',
                candidate.profile_id,
                gen_random_uuid(),
                jsonb_build_object(
                    'category', 'SYSTEM',
                    'source', 'V36',
                    'profileId', candidate.profile_id,
                    'positionId', candidate.position_id,
                    'authorizationScopeType', candidate.authorization_scope_type,
                    'permissionCount', expected_permission_count
                )
            );
        END LOOP;
    END LOOP;
END $$;

ALTER TABLE tenant FORCE ROW LEVEL SECURITY;
